# Generated by Django 5.1.2 on 2024-11-29 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('platform', models.CharField(max_length=100)),
                ('quantity_sold', models.PositiveIntegerField()),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_sale_value', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('date_of_sale', models.DateField(db_index=True)),
                ('coupon_used', models.BooleanField(blank=True, default=False, null=True)),
                ('return_window', models.IntegerField(blank=True, null=True)),
                ('prime_delivery', models.BooleanField(blank=True, default=False, null=True)),
                ('warehouse_location', models.CharField(blank=True, max_length=50, null=True)),
                ('reseller_name', models.CharField(blank=True, max_length=255, null=True)),
                ('commission_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='sales.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address_street', models.CharField(max_length=255)),
                ('delivery_address_city', models.CharField(max_length=100)),
                ('delivery_address_state', models.CharField(db_index=True, max_length=100)),
                ('delivery_address_pin_code', models.CharField(max_length=10)),
                ('delivery_date', models.DateField(db_index=True)),
                ('delivery_status', models.CharField(choices=[('Delivered', 'Delivered'), ('In Transit', 'In Transit'), ('Cancelled', 'Cancelled')], db_index=True, max_length=20)),
                ('delivery_partner', models.CharField(max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='sales.order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('category', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'indexes': [models.Index(fields=['category'], name='idx_category')],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='sales.product'),
        ),
    ]
